// Display names that the backend deliberately does not own: service group
// names and Chinese overrides for cloud-nuke resource-type labels.

const serviceNames: Record<string, { en: string; zh: string }> = {
  ec2: { en: "EC2", zh: "EC2" },
  vpc: { en: "VPC", zh: "VPC" },
  "load-balancing": { en: "Load balancing", zh: "负载均衡" },
  containers: { en: "Containers", zh: "容器" },
  serverless: { en: "Serverless", zh: "无服务器" },
  databases: { en: "Databases", zh: "数据库" },
  storage: { en: "Storage", zh: "存储" },
  messaging: { en: "Messaging & streams", zh: "消息与流" },
  monitoring: { en: "Monitoring", zh: "监控" },
  devtools: { en: "Developer tools", zh: "开发者工具" },
  ml: { en: "Machine learning", zh: "机器学习" },
  security: { en: "Security & keys", zh: "安全与密钥" },
  iam: { en: "IAM", zh: "IAM" },
  "edge-dns": { en: "Edge & DNS", zh: "边缘与 DNS" },
  other: { en: "Other", zh: "其他" },
};

export function serviceName(id: string, lang: string): string {
  const s = serviceNames[id];
  if (!s) return id;
  return lang.startsWith("zh") ? s.zh : s.en;
}

const zhTypeLabels: Record<string, string> = {
  ec2: "EC2 实例",
  asg: "Auto Scaling 组",
  "launch-configuration": "启动配置",
  "launch-template": "启动模板",
  ebs: "EBS 卷",
  "ebs-snapshot": "EBS 快照",
  ami: "AMI 镜像",
  eip: "弹性 IP",
  "ec2-keypairs": "密钥对",
  "ec2-placement-groups": "置放群组",
  "ec2-dedicated-hosts": "专用主机",
  "elastic-beanstalk": "Elastic Beanstalk 环境",
  vpc: "VPC",
  "ec2-subnet": "子网",
  "security-group": "安全组",
  "network-acl": "网络 ACL",
  "ec2-endpoint": "VPC 终端节点",
  "nat-gateway": "NAT 网关",
  "internet-gateway": "互联网网关",
  "egress-only-internet-gateway": "仅出站互联网网关",
  "network-interface": "网络接口",
  "route-table": "路由表",
  "ec2-dhcp-option": "DHCP 选项集",
  "vpc-peering-connection": "VPC 对等连接",
  "transit-gateway": "Transit Gateway",
  elb: "Classic 负载均衡器",
  elbv2: "应用/网络负载均衡器",
  "ecs-cluster": "ECS 集群",
  "ecs-service": "ECS 服务",
  "eks-cluster": "EKS 集群",
  ecr: "ECR 仓库",
  "app-runner-service": "App Runner 服务",
  lambda: "Lambda 函数",
  "lambda-layer": "Lambda 层",
  "api-gateway": "API Gateway (REST)",
  "api-gateway-v2": "API Gateway (HTTP/WebSocket)",
  "rds-instance": "RDS 实例",
  "rds-cluster": "RDS/Aurora 集群",
  "rds-snapshot": "RDS 快照",
  "rds-cluster-snapshot": "RDS 集群快照",
  "rds-parameter-group": "RDS 参数组",
  "rds-subnet-group": "RDS 子网组",
  "rds-proxy": "RDS 代理",
  dynamodb: "DynamoDB 表",
  elasticache: "ElastiCache 集群",
  redshift: "Redshift 集群",
  "opensearch-domain": "OpenSearch 域",
  s3: "S3 存储桶",
  "s3-access-point": "S3 访问点",
  efs: "EFS 文件系统",
  "backup-plan": "AWS Backup 计划",
  "backup-vault": "AWS Backup 保管库",
  sqs: "SQS 队列",
  "sns-topic": "SNS 主题",
  "event-bridge": "EventBridge 事件总线",
  "event-bridge-rule": "EventBridge 规则",
  "kinesis-stream": "Kinesis 数据流",
  "kinesis-firehose": "Kinesis Firehose",
  "msk-cluster": "MSK 集群",
  "mq-broker": "Amazon MQ 代理",
  "cloudwatch-loggroup": "CloudWatch 日志组",
  "cloudwatch-alarm": "CloudWatch 告警",
  "cloudwatch-dashboard": "CloudWatch 仪表板",
  cloudtrail: "CloudTrail 跟踪",
  "cloudformation-stack": "CloudFormation 堆栈",
  "ssm-parameter": "SSM 参数",
  "secrets-manager": "Secrets Manager 密钥",
  "kms-customer-key": "KMS 客户密钥（7 天待删除）",
  acm: "ACM 证书",
  "guard-duty": "GuardDuty 检测器",
  "iam-user": "IAM 用户",
  "iam-group": "IAM 组",
  "iam-role": "IAM 角色",
  "iam-policy": "IAM 自定义策略",
  "iam-instance-profile": "IAM 实例配置文件",
  "iam-service-linked-role": "IAM 服务关联角色",
  "oidc-provider": "IAM OIDC 提供商",
  "cloudfront-distribution": "CloudFront 分配",
  "route53-hosted-zone": "Route 53 托管区域",
};

export function typeLabel(id: string, enLabel: string, lang: string): string {
  if (lang.startsWith("zh") && zhTypeLabels[id]) return zhTypeLabels[id];
  return enLabel;
}
